### ISSUE TITLE
query without positive atom does not advance iterator

### ISSUE THREAD

**Issue by hanwen** [google/zoekt#28]
017/07/25 23:15:12 got query "r:bazel lang:python"
2017/07/25 23:15:12 lastDoc 90, nextDoc 90
2017/07/25 23:15:12 lastDoc 809, nextDoc 809
2017/07/25 23:15:12 lastDoc 134, nextDoc 134
2017/07/25 23:15:12 lastDoc 36, nextDoc 36
2017/07/25 23:15:12 lastDoc 152, nextDoc 152
2017/07/25 23:15:12 crashed shard: shard(/zoekt/index/github.com%2Fbazelbuild%2Fbazel_v14.00000.zoekt): lastDoc 90, nextDoc 90, goroutine 7895054604 [running]:
runtime/debug.Stack(0xc5ea7796e0, 0xc598d4def0, 0x43)
        /usr/lib/google-golang/src/runtime/debug/stack.go:24 +0x79
github.com/google/zoekt/shards.(*shardedSearcher).Search.func1.1(0xc47d23c580, 0x9d0fe0, 0xc5ea7796e0, 0xc6870ec120)
        /usr/local/google/home/hanwen/go/src/github.com/google/zoekt/shards/shards.go:118 +0xc2
panic(0x78e2e0, 0xc44dfe8890)
        /usr/lib/google-golang/src/runtime/panic.go:489 +0x2e1
log.Panicf(0x825dbb, 0x16, 0xc7296aec70, 0x2, 0x2)
        /usr/lib/google-golang/src/log/log.go:329 +0xda
github.com/google/zoekt.(*indexData).Search(0xc4be9b5180, 0x7f70a27fb040, 0xc6870ec1e0, 0x9cb1e0, 0xc674805700, 0xc426027c20, 0xc60b8e7f30, 0xc60b8e7f28, 0xc7776df630)
        /usr/local/google/home/hanwen/go/src/github.com/google/zoekt/eval.go:668 +0x1638
github.com/google/zoekt/shards.(*searchShard).Search(0xc5ea7796e0, 0x7f70a27fb040, 0xc6870ec1e0, 0x9cb1e0, 0xc674805700, 0xc426027c20, 0x9cb260, 0xc4241010fa, 0xc42cdb8e80)
        <autogenerated>:5 +0x82
github.com/google/zoekt/shards.(*shardedSearcher).Search.func1(0xc47d23c580, 0xc6870ec120, 0xc490a4dee0, 0x9cb1e0, 0xc674805700, 0xc426027c20, 0x9d0fe0, 0xc5ea7796e0)
        /usr/local/google/home/hanwen/go/src/github.com/google/zoekt/shards/shards.go:126 +0xf9
created by github.com/google/zoekt/shards.(*shardedSearcher).Search
        /usr/local/google/home/hanwen/go/src/github.com/google/zoekt/shards/shards.go:128 +0x404

**Comment by hanwen** [comment]
fixed in https://github.com/google/zoekt/commit/7eea5e105c1101e3f16e46df8148b53a9b7c75c4
